version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./data/www:/mnt/code
      - ./data/logs/nginx.logs:/var/log/nginx
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/fastcgi_params:/etc/nginx/fastcgi_params
    links:   
      - myphp
    networks:
      - webnet
  myphp:
    build: ./php
    volumes:
      - ./data/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./data/php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./data/logs/php.logs:/var/log/php
      - ./data/www:/mnt/code
    ports:
      - "9000:9000"
    expose:
      - 9000
    networks:
      - webnet
  mysql:
    image: mysql:5.7
    ports:
      - "33060:3306"
    volumes:
      - ./data/mysql/conf:/etc/mysql
      - ./data/mysql/logs:/var/log
      - ./data/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet 
networks:
  webnet: